[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:django]
command=gunicorn config.wsgi:application --bind 0.0.0.0:%(ENV_PORT)s
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:telegram-bot]
command=python telegram_bot.py
directory=/opt/render/project/src
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
