# Generated by Django 5.0 on 2025-12-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], max_length=10)),
                ('illness_description', models.TextField()),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('threat_level', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('created', 'Создан'), ('sent_to_doctors', 'Отправлен врачам'), ('accepted', 'Принят врачом'), ('on_way', 'Врач в пути'), ('on_site', 'Врач на месте'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('on_site_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report_photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('report_text', models.TextField(blank=True)),
                ('ambulance_called', models.BooleanField(default=False)),
                ('ambulance_called_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='dispatcher.doctor')),
            ],
            options={
                'verbose_name': 'Вызов',
                'verbose_name_plural': 'Вызовы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('distance', models.FloatField(help_text='Расстояние в км')),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dispatcher.call')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dispatcher.doctor')),
            ],
            options={
                'verbose_name': 'Ответ на вызов',
                'verbose_name_plural': 'Ответы на вызовы',
                'unique_together': {('call', 'doctor')},
            },
        ),
    ]
